import Head from "next/head";

import CreateBar from "../src/@core/components/create-header/CreateBar";
import JobList from "../src/@core/components/job-list";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CreateBar />
      <JobList />
    </div>
  );
}
